package view.reservas;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Parley
 */
public abstract class ReservaPatrimonio extends javax.swing.JDialog {

	
	public ReservaPatrimonio(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	protected Vector<String> fillDataVector(String horario) {

		Vector<String> nomesTabela = new Vector<String>();
		nomesTabela.add(horario);
		return nomesTabela;

	}

	protected DefaultTableModel fillTable() {

		final int NUMERO_LINHAS = 7;
		int i = 0;
		DefaultTableModel table = new DefaultTableModel();

		table.addColumn("HORARIO");
		table.addColumn("Segunda");
		table.addColumn("Ter�a");
		table.addColumn("Quarta");
		table.addColumn("Quinta");
		table.addColumn("Sexta");
		table.addColumn("Sabado");
		
		int a = 8, b = 10;
		
		while (i < NUMERO_LINHAS) {
			
			String horario = "" + a + " - " + b;
			table.addRow(fillDataVector(horario));
			a=b;
			b+=2;
			i++;
		}
		
		return table;
	}
	
	protected abstract void reservarAction();
	
	protected abstract void cancelarReservaAction();
	
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ReservarBtn = new javax.swing.JButton();
                CancelarReservaBtn = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                TabelaHorarios = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setResizable(false);

                ReservarBtn.setText("Reservar");
                ReservarBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReservarBtnActionPerformed(evt);
                        }
                });

                CancelarReservaBtn.setText("Cancelar Reserva");
                CancelarReservaBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CancelarReservaBtnActionPerformed(evt);
                        }
                });

                TabelaHorarios.setAutoCreateRowSorter(true);
                TabelaHorarios.setModel(fillTable());
                TabelaHorarios.setCellSelectionEnabled(true);
                TabelaHorarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                TabelaHorarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jScrollPane1.setViewportView(TabelaHorarios);
                for(int i = 0; i < this.TabelaHorarios.getRowCount(); i++){
                        this.TabelaHorarios.setRowHeight(i, 100);
                }

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ReservarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CancelarReservaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(ReservarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelarReservaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void ReservarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBtnActionPerformed
                reservarAction();
        }//GEN-LAST:event_ReservarBtnActionPerformed

        private void CancelarReservaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarReservaBtnActionPerformed
                cancelarReservaAction();
        }//GEN-LAST:event_CancelarReservaBtnActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton CancelarReservaBtn;
        private javax.swing.JButton ReservarBtn;
        private javax.swing.JTable TabelaHorarios;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables
}
