package view.reservas;

import java.util.Iterator;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Parley
 */
public class ReservaPatrimonio extends javax.swing.JDialog {

	
	public ReservaPatrimonio(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	protected Vector<String> fillDataVector() {

		Vector<String> nomesTabela = new Vector<String>();

		return nomesTabela;

	}

	protected DefaultTableModel fillTable() {
		DefaultTableModel table = new DefaultTableModel();

		//Iterator<Cliente> i = getIterator();

		table.addColumn("");
		table.addColumn("Segunda");
		table.addColumn("Terça");
		table.addColumn("Quarta");
		table.addColumn("Quinta");
		table.addColumn("Sexta");
		table.addColumn("Sábado");
		
		
/*
		while (i.hasNext()) {
			
			Cliente cliente = i.next();
			table.addRow(fillDataVector(cliente));
		}
*/
		return table;
	}
	
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ReservarBtn = new javax.swing.JButton();
                CancelarReservaBtn = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                TabelaHorarios = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                ReservarBtn.setText("Reservar");

                CancelarReservaBtn.setText("Cancelar Reserva");

                TabelaHorarios.setAutoCreateRowSorter(true);
                TabelaHorarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                jScrollPane1.setViewportView(TabelaHorarios);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ReservarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CancelarReservaBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(ReservarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelarReservaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton CancelarReservaBtn;
        private javax.swing.JButton ReservarBtn;
        private javax.swing.JTable TabelaHorarios;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables
}
